name       : python-cffi
version    : 1.15.1
release    : 15
source     :
    - https://pypi.io/packages/source/c/cffi/cffi-1.15.1.tar.gz : d400bfb9a37b1351253cb402671cea7e89bdecc294e8016a707f6d1d8ac934f9
homepage   : http://cffi.readthedocs.org
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
rundeps    :
    - python-cparser
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_distutils_api and not test_setuptools'
