name       : python-cffi
version    : 1.13.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/0d/aa/c5ac2f337d9a10ee95d160d47beb8d9400e1b2a46bb94990a0409fe6d133/cffi-1.13.1.tar.gz : 558b3afef987cf4b17abd849e7bedf64ee12b28175d564d05b628a0f9355599b
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cparser
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test py.test -v -k 'not test_distutils_api and not test_setuptools'
#    %python3_test py.test3 -v -k 'not test_distutils_api and not test_setuptools'
