name       : python-cffi
version    : 1.14.5
release    : 9
source     :
    - https://pypi.io/packages/source/c/cffi/cffi-1.14.5.tar.gz : fd78e5fee591709f32ef6edb9a015b4aa1a5022598e36227500c8f4e02328d9c
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cparser
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v -k 'not test_distutils_api and not test_setuptools'
    %python3_test py.test3 -v -k 'not test_distutils_api and not test_setuptools'
