name       : python-cffi
version    : 1.14.6
release    : 10
source     :
    - https://pypi.io/packages/source/c/cffi/cffi-1.14.6.tar.gz : c9a875ce9d7fe32887784274dd533c57909b7b1dcadcc128a2ac21331a9765dd
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
rundeps    :
    - python-cparser
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_distutils_api and not test_setuptools'
