name       : python-cffi
version    : 1.11.5
release    : 5
source     :
    - https://pypi.io/packages/source/c/cffi/cffi-1.11.5.tar.gz : e90f17980e6ab0f3c2f3730e56d1fe9bcba1891eeea58966e89d352492cc74f4
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cparser
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v -k 'not test_distutils_api and not test_setuptools'
    %python3_test py.test3 -v -k 'not test_distutils_api and not test_setuptools'
