name       : python-cffi
version    : 1.11.1
release    : 3
source     :
    - https://pypi.io/packages/source/c/cffi/cffi-1.11.1.tar.gz : 4c40817cc0f71b5351eb0bdd0b585db4a285c2bcc03fbcb961b79bb8086b7576
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cparser
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot%
    done
check      : |
    for py in "python" "python3" ; do
        ${py} setup.py test
        ${py} -m pytest -v --ignore="testing/cffi1/test_zdist.py"
    done
