name       : python-cffi
version    : 1.5.2
release    : 1
source     :
    - https://pypi.python.org/packages/source/c/cffi/cffi-1.5.2.tar.gz : da9bde99872e46f7bb5cff40a9b1cc08406765efafb583c704de108b6cb821dd
license    : MIT
summary    : Foreign Function Interface for Python calling C code.
description: |
    Foreign Function Interface for Python calling C code.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
