name       : python-cffi
version    : 1.15.0
release    : 14
source     :
    - https://pypi.io/packages/source/c/cffi/cffi-1.15.0.tar.gz : 920f0d66a896c2d99f0adbb391f990a84091179542c205fa53ce5787aff87954
license    : MIT
component  : programming.python
summary    : Foreign Function Interface for Python calling C code
description: |
    C Foreign Function Interface for Python. Interact with almost any C code from Python, based on C-like declarations that you can often copy-paste from header files or documentation.
builddeps  :
    - pkgconfig(python3)
    - python-cparser
    - python-pytest
rundeps    :
    - python-cparser
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not test_distutils_api and not test_setuptools'
